/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MeuPrimeiroProjeto;

public class App {
    
 

    public static void main(String[] args) {
        
        //Comentário de linha.
        
        /*
            Comentário em bloco, pode ser várias linhas
        não precisa usar o // que nem no outro exemplo de comentário.
        */
        
        /**
         * Comentário em bloco, mas, é pra ser usado em uma documentação
         * posteriormente posso usar um app de terceiros e extrair esse 
         * e esse comentário e gerar uma documentação
         */
        System.out.println("Olá mundo hehe");
    }
}
